"""first push

Revision ID: 00687322b2fd
Revises: 9c6c42fa5035
Create Date: 2020-05-05 01:01:28.951664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00687322b2fd'
down_revision = '9c6c42fa5035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('annotation_1_id', sa.Integer(), nullable=True),
    sa.Column('annotation_2_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_1_id'], ['sf_ctakes_mentions.id'], ),
    sa.ForeignKeyConstraint(['annotation_2_id'], ['sf_ctakes_mentions.id'], ),
    sa.UniqueConstraint('annotation_1_id', 'annotation_2_id', name='unique_relationships')
    )
    op.create_index(op.f('ix_friendships_annotation_1_id'), 'friendships', ['annotation_1_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_annotation_1_id'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
