"""first push

Revision ID: 4c323fb4b581
Revises: 5e1bb441d442
Create Date: 2020-05-05 23:40:08.539785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c323fb4b581'
down_revision = '5e1bb441d442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_relationships_file_id_fkey', 'annotation_relationships', type_='foreignkey')
    op.drop_constraint('annotation_relationships_file_state_id_fkey', 'annotation_relationships', type_='foreignkey')
    op.drop_column('annotation_relationships', 'file_state_id')
    op.drop_column('annotation_relationships', 'file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('annotation_relationships', sa.Column('file_state_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('annotation_relationships_file_state_id_fkey', 'annotation_relationships', 'file_state', ['file_state_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('annotation_relationships_file_id_fkey', 'annotation_relationships', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
