"""first push

Revision ID: 56f0eee69626
Revises: b6fc7277082e
Create Date: 2020-05-08 19:29:37.818093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f0eee69626'
down_revision = 'b6fc7277082e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('relation_type', sa.String(), nullable=True))
    op.drop_column('annotation_relationships', 'relation_Category')
    op.drop_column('sf_ctakes_mentions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_ctakes_mentions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('annotation_relationships', sa.Column('relation_Category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('annotation_relationships', 'relation_type')
    # ### end Alembic commands ###
