"""first push

Revision ID: 5e1bb441d442
Revises: 89e0f2d4bb54
Create Date: 2020-05-05 23:38:23.998409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1bb441d442'
down_revision = '89e0f2d4bb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('annotation_relationships', 'annotation_1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('annotation_relationships', 'annotation_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_annotation_relationships_annotation_2_id'), 'annotation_relationships', ['annotation_2_id'], unique=False)
    op.create_index(op.f('ix_annotation_relationships_id'), 'annotation_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_relationships_id'), table_name='annotation_relationships')
    op.drop_index(op.f('ix_annotation_relationships_annotation_2_id'), table_name='annotation_relationships')
    op.alter_column('annotation_relationships', 'annotation_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('annotation_relationships', 'annotation_1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('annotation_relationships', 'id')
    # ### end Alembic commands ###
