"""first push

Revision ID: 5ef2999165f0
Revises: 
Create Date: 2020-03-30 23:29:15.732635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ef2999165f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'modified_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'modified_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
