"""first push

Revision ID: 64488353f71a
Revises: cff9028cb698
Create Date: 2020-05-06 20:15:45.064230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64488353f71a'
down_revision = 'cff9028cb698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_relationships_annotation_1_id_fkey', 'annotation_relationships', type_='foreignkey')
    op.drop_constraint('annotation_relationships_annotation_2_id_fkey', 'annotation_relationships', type_='foreignkey')
    op.create_foreign_key(None, 'annotation_relationships', 'sf_ctakes_mentions', ['annotation_1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'annotation_relationships', 'sf_ctakes_mentions', ['annotation_2_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_relationships', type_='foreignkey')
    op.drop_constraint(None, 'annotation_relationships', type_='foreignkey')
    op.create_foreign_key('annotation_relationships_annotation_2_id_fkey', 'annotation_relationships', 'sf_ctakes_mentions', ['annotation_2_id'], ['id'])
    op.create_foreign_key('annotation_relationships_annotation_1_id_fkey', 'annotation_relationships', 'sf_ctakes_mentions', ['annotation_1_id'], ['id'])
    # ### end Alembic commands ###
