"""first push

Revision ID: 73e902758134
Revises: 187e21bc129f
Create Date: 2020-05-05 23:25:24.569325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e902758134'
down_revision = '187e21bc129f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
