"""first push

Revision ID: 747f4ddd46d0
Revises: 00687322b2fd
Create Date: 2020-05-05 01:12:50.035585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '747f4ddd46d0'
down_revision = '00687322b2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_relationships',
    sa.Column('annotation_1_id', sa.Integer(), nullable=True),
    sa.Column('annotation_2_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_1_id'], ['sf_ctakes_mentions.id'], ),
    sa.ForeignKeyConstraint(['annotation_2_id'], ['sf_ctakes_mentions.id'], ),
    sa.UniqueConstraint('annotation_1_id', 'annotation_2_id', name='unique_annot_relationship')
    )
    op.create_index(op.f('ix_annotation_relationships_annotation_1_id'), 'annotation_relationships', ['annotation_1_id'], unique=False)
    op.drop_index('ix_friendships_annotation_1_id', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('annotation_1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annotation_2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['annotation_1_id'], ['sf_ctakes_mentions.id'], name='friendships_annotation_1_id_fkey'),
    sa.ForeignKeyConstraint(['annotation_2_id'], ['sf_ctakes_mentions.id'], name='friendships_annotation_2_id_fkey'),
    sa.UniqueConstraint('annotation_1_id', 'annotation_2_id', name='unique_relationships')
    )
    op.create_index('ix_friendships_annotation_1_id', 'friendships', ['annotation_1_id'], unique=False)
    op.drop_index(op.f('ix_annotation_relationships_annotation_1_id'), table_name='annotation_relationships')
    op.drop_table('annotation_relationships')
    # ### end Alembic commands ###
