"""first push

Revision ID: 89e0f2d4bb54
Revises: 73e902758134
Create Date: 2020-05-05 23:30:07.087378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e0f2d4bb54'
down_revision = '73e902758134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_annot_relationship', 'annotation_relationships', ['annotation_1_id', 'annotation_2_id'])
    op.drop_index('ix_annotation_relationships_id', table_name='annotation_relationships')
    op.drop_column('annotation_relationships', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_annotation_relationships_id', 'annotation_relationships', ['id'], unique=False)
    op.drop_constraint('unique_annot_relationship', 'annotation_relationships', type_='unique')
    # ### end Alembic commands ###
