"""first push

Revision ID: 9152fe635a2e
Revises: 747f4ddd46d0
Create Date: 2020-05-05 22:05:23.173884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9152fe635a2e'
down_revision = '747f4ddd46d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('annotation_relationships', sa.Column('file_id', sa.Integer(), nullable=False))
    op.add_column('annotation_relationships', sa.Column('file_state_id', sa.Integer(), nullable=False))
    op.add_column('annotation_relationships', sa.Column('relation_Category', sa.String(), nullable=True))
    op.create_foreign_key(None, 'annotation_relationships', 'business', ['business_id'], ['id'])
    op.create_foreign_key(None, 'annotation_relationships', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'annotation_relationships', 'file_state', ['file_state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_relationships', type_='foreignkey')
    op.drop_constraint(None, 'annotation_relationships', type_='foreignkey')
    op.drop_constraint(None, 'annotation_relationships', type_='foreignkey')
    op.drop_column('annotation_relationships', 'relation_Category')
    op.drop_column('annotation_relationships', 'file_state_id')
    op.drop_column('annotation_relationships', 'file_id')
    op.drop_column('annotation_relationships', 'business_id')
    # ### end Alembic commands ###
