"""first push

Revision ID: b6fc7277082e
Revises: 8a85b07d8c1e
Create Date: 2020-05-08 18:36:19.417437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fc7277082e'
down_revision = '8a85b07d8c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_annot_relationship', 'annotation_relationships', type_='unique')
    op.create_unique_constraint('unique_annot_relationship', 'annotation_relationships', ['annotation_1_id', 'annotation_2_id'])
    op.drop_constraint('annotation_relationships_business_id_fkey', 'annotation_relationships', type_='foreignkey')
    op.drop_column('annotation_relationships', 'business_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('annotation_relationships_business_id_fkey', 'annotation_relationships', 'business', ['business_id'], ['id'])
    op.drop_constraint('unique_annot_relationship', 'annotation_relationships', type_='unique')
    op.create_unique_constraint('unique_annot_relationship', 'annotation_relationships', ['annotation_1_id', 'annotation_2_id', 'id'])
    # ### end Alembic commands ###
