"""first push

Revision ID: cff9028cb698
Revises: 4c323fb4b581
Create Date: 2020-05-06 18:27:23.202830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cff9028cb698'
down_revision = '4c323fb4b581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotation_relationships_id', table_name='annotation_relationships')
    op.drop_column('annotation_relationships', 'id')
    op.add_column('sf_ctakes_mentions', sa.Column('body_region', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sf_ctakes_mentions', 'body_region')
    op.add_column('annotation_relationships', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_annotation_relationships_id', 'annotation_relationships', ['id'], unique=False)
    # ### end Alembic commands ###
