"""first push

Revision ID: eefa29866e92
Revises: 5b452e7452d1
Create Date: 2020-05-08 19:40:21.623894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefa29866e92'
down_revision = '5b452e7452d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotation_relationships_id', table_name='annotation_relationships')
    op.drop_column('annotation_relationships', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_relationships', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_annotation_relationships_id', 'annotation_relationships', ['id'], unique=False)
    # ### end Alembic commands ###
