// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ziLxYvEoJ",
    "aws_user_pools_web_client_id": "1cgb0jcjqmi710e370s80lq115",
    "oauth": {}
};


export default awsmobile;
